name: Build and Deploy Frontend app to demo environment

on:
  push:
    paths:
      - 'app/frontend/**'
      - '.github/workflows/**'

jobs:
  build-frontend-app:
    uses: ./.github/workflows/common_frontend.yml
    with:
      APP_LOCATION: app/frontend
      OUTPUT_LOCATION: build
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_MOSS_080CD250F: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_MOSS_080CD250F }}